name: Auto GAE Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: atRobertoFlores/gae_deploy_action@1.2
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          project_name: ${{ secrets.PROJECT_NAME }}
