name: Auto GAE Deploy

on: [push]

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: atRobertoFlores/gae_deploy_action@1.2
      with:
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        project_name: ${{ secrets.PROJECT_NAME }}
